service:
  name: malcoded-vue

# # Add the serverless-webpack plugin
plugins:
  - serverless-plugin-warmup

# package:
#   individually: true
#   include:
#     - yarn.lock

package:
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - lambda:InvokeFunction
      Resource: "*"

functions:
  main:
    handler: handler.main
    warmup: true
    events:
      - http: ANY /
      - http: ANY /{proxy+}
